/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as counterSol from "./Counter.sol";
export type { counterSol };
export type { GovernanceToken } from "./GovernanceToken";
