/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ProposalVoting {
  export type AmendmentStruct = {
    proposalId: BigNumberish;
    title: string;
    description: string;
    proposedBy: AddressLike;
    timestamp: BigNumberish;
    approved: boolean;
    status: string;
  };

  export type AmendmentStructOutput = [
    proposalId: bigint,
    title: string,
    description: string,
    proposedBy: string,
    timestamp: bigint,
    approved: boolean,
    status: string
  ] & {
    proposalId: bigint;
    title: string;
    description: string;
    proposedBy: string;
    timestamp: bigint;
    approved: boolean;
    status: string;
  };
}

export interface ProposalVotingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_TOKEN_TO_VOTE"
      | "amendments"
      | "approveAmendment"
      | "approveExecution"
      | "assignRole"
      | "createProposal"
      | "delegateVote"
      | "delegators"
      | "executeProposal"
      | "executionApprovals"
      | "getAmendment"
      | "getDelegate"
      | "getEffectiveVotingPower"
      | "getMultiSigDetails"
      | "getProposal"
      | "getProposalAmendments"
      | "getProposalCount"
      | "getProposalSnapshotBlock"
      | "getProposals"
      | "getProposalsByCategory"
      | "getProposalsByStatus"
      | "getUserRole"
      | "getVote"
      | "getVoterSnapshotBalance"
      | "getVoterStats"
      | "governanceToken"
      | "hasRole"
      | "hasVoted"
      | "multiSigApprovers"
      | "owner"
      | "proposalAmendments"
      | "proposals"
      | "proposalsByCategory"
      | "proposeAmendment"
      | "rejectAmendment"
      | "requestExecution"
      | "requiredApprovals"
      | "revokeDelegation"
      | "revokeRole"
      | "userRoles"
      | "vote"
      | "voteDelegation"
      | "voterSnapshotBalance"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AmendmentApproved"
      | "AmendmentProposed"
      | "AmendmentRejected"
      | "ExecutionApproved"
      | "ExecutionRequested"
      | "MultiSigSetup"
      | "ProposalCreated"
      | "ProposalExecuted"
      | "ProposalRejected"
      | "RoleAssigned"
      | "RoleRevoked"
      | "VoteCasted"
      | "VoteDelegated"
      | "VoteDelegationRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_TOKEN_TO_VOTE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "amendments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveAmendment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "assignRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "delegateVote",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "delegators",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executionApprovals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAmendment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDelegate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEffectiveVotingPower",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultiSigDetails",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalAmendments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalSnapshotBlock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByCategory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposalsByStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterSnapshotBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoterStats",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "governanceToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "multiSigApprovers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalAmendments",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalsByCategory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeAmendment",
    values: [BigNumberish, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectAmendment",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestExecution",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requiredApprovals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeDelegation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userRoles",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "voteDelegation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voterSnapshotBalance",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_TOKEN_TO_VOTE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "amendments", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveAmendment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assignRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delegators", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executionApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAmendment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDelegate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEffectiveVotingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultiSigDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalAmendments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalSnapshotBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposalsByStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoterSnapshotBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVoterStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governanceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiSigApprovers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalAmendments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalsByCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeAmendment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectAmendment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestExecution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requiredApprovals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userRoles", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteDelegation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voterSnapshotBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace AmendmentApprovedEvent {
  export type InputTuple = [
    amendmentId: BigNumberish,
    proposalId: BigNumberish
  ];
  export type OutputTuple = [amendmentId: bigint, proposalId: bigint];
  export interface OutputObject {
    amendmentId: bigint;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmendmentProposedEvent {
  export type InputTuple = [
    amendmentId: BigNumberish,
    proposalId: BigNumberish,
    proposedBy: AddressLike
  ];
  export type OutputTuple = [
    amendmentId: bigint,
    proposalId: bigint,
    proposedBy: string
  ];
  export interface OutputObject {
    amendmentId: bigint;
    proposalId: bigint;
    proposedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AmendmentRejectedEvent {
  export type InputTuple = [
    amendmentId: BigNumberish,
    proposalId: BigNumberish
  ];
  export type OutputTuple = [amendmentId: bigint, proposalId: bigint];
  export interface OutputObject {
    amendmentId: bigint;
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionApprovedEvent {
  export type InputTuple = [proposalId: BigNumberish, approver: AddressLike];
  export type OutputTuple = [proposalId: bigint, approver: string];
  export interface OutputObject {
    proposalId: bigint;
    approver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutionRequestedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MultiSigSetupEvent {
  export type InputTuple = [approvers: AddressLike[], required: BigNumberish];
  export type OutputTuple = [approvers: string[], required: bigint];
  export interface OutputObject {
    approvers: string[];
    required: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    title: string,
    creator: AddressLike,
    deadline: BigNumberish,
    category: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    title: string,
    creator: string,
    deadline: bigint,
    category: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    title: string;
    creator: string;
    deadline: bigint;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalRejectedEvent {
  export type InputTuple = [proposalId: BigNumberish];
  export type OutputTuple = [proposalId: bigint];
  export interface OutputObject {
    proposalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAssignedEvent {
  export type InputTuple = [user: AddressLike, role: BigNumberish];
  export type OutputTuple = [user: string, role: bigint];
  export interface OutputObject {
    user: string;
    role: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    support: boolean,
    tokenWeight: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    support: boolean,
    tokenWeight: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    support: boolean;
    tokenWeight: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteDelegatedEvent {
  export type InputTuple = [delegator: AddressLike, delegate: AddressLike];
  export type OutputTuple = [delegator: string, delegate: string];
  export interface OutputObject {
    delegator: string;
    delegate: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteDelegationRevokedEvent {
  export type InputTuple = [delegator: AddressLike];
  export type OutputTuple = [delegator: string];
  export interface OutputObject {
    delegator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ProposalVoting extends BaseContract {
  connect(runner?: ContractRunner | null): ProposalVoting;
  waitForDeployment(): Promise<this>;

  interface: ProposalVotingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_TOKEN_TO_VOTE: TypedContractMethod<[], [bigint], "view">;

  amendments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, string] & {
        proposalId: bigint;
        title: string;
        description: string;
        proposedBy: string;
        timestamp: bigint;
        approved: boolean;
        status: string;
      }
    ],
    "view"
  >;

  approveAmendment: TypedContractMethod<
    [_amendmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  approveExecution: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  assignRole: TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;

  createProposal: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _duration: BigNumberish,
      _category: string
    ],
    [void],
    "nonpayable"
  >;

  delegateVote: TypedContractMethod<
    [_delegate: AddressLike],
    [void],
    "nonpayable"
  >;

  delegators: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  executeProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executionApprovals: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  getAmendment: TypedContractMethod<
    [_amendmentId: BigNumberish],
    [ProposalVoting.AmendmentStructOutput],
    "view"
  >;

  getDelegate: TypedContractMethod<[_voter: AddressLike], [string], "view">;

  getEffectiveVotingPower: TypedContractMethod<
    [_voter: AddressLike],
    [bigint],
    "view"
  >;

  getMultiSigDetails: TypedContractMethod<
    [],
    [[string[], bigint] & { approvers: string[]; required: bigint }],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_proposalId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        yesVotes: bigint;
        noVotes: bigint;
        deadline: bigint;
        status: string;
        creator: string;
        isVotingOpen: boolean;
        category: string;
        approvalsGiven: bigint;
      }
    ],
    "view"
  >;

  getProposalAmendments: TypedContractMethod<
    [_proposalId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getProposalCount: TypedContractMethod<[], [bigint], "view">;

  getProposalSnapshotBlock: TypedContractMethod<
    [_proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  getProposals: TypedContractMethod<
    [],
    [
      [
        string[],
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        string[]
      ] & {
        titles: string[];
        descriptions: string[];
        yesVotes: bigint[];
        noVotes: bigint[];
        deadlines: bigint[];
        statuses: string[];
        creators: string[];
        categories: string[];
      }
    ],
    "view"
  >;

  getProposalsByCategory: TypedContractMethod<
    [_category: string],
    [bigint[]],
    "view"
  >;

  getProposalsByStatus: TypedContractMethod<
    [_status: BigNumberish],
    [bigint[]],
    "view"
  >;

  getUserRole: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  getVote: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasVoted: boolean;
        support: boolean;
        tokenWeight: bigint;
      }
    ],
    "view"
  >;

  getVoterSnapshotBalance: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [bigint],
    "view"
  >;

  getVoterStats: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [
      [boolean, bigint, bigint] & {
        participated: boolean;
        tokenUsed: bigint;
        votingPower: bigint;
      }
    ],
    "view"
  >;

  governanceToken: TypedContractMethod<[], [string], "view">;

  hasRole: TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [boolean],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;

  multiSigApprovers: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalAmendments: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        title: string;
        description: string;
        yesVotes: bigint;
        noVotes: bigint;
        deadline: bigint;
        status: bigint;
        creator: string;
        category: string;
        snapshotBlock: bigint;
        readyForExecution: boolean;
        amendmentCount: bigint;
      }
    ],
    "view"
  >;

  proposalsByCategory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  proposeAmendment: TypedContractMethod<
    [_proposalId: BigNumberish, _title: string, _description: string],
    [void],
    "nonpayable"
  >;

  rejectAmendment: TypedContractMethod<
    [_amendmentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestExecution: TypedContractMethod<
    [_proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  requiredApprovals: TypedContractMethod<[], [bigint], "view">;

  revokeDelegation: TypedContractMethod<[], [void], "nonpayable">;

  revokeRole: TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;

  userRoles: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  vote: TypedContractMethod<
    [_proposalId: BigNumberish, _support: boolean],
    [void],
    "nonpayable"
  >;

  voteDelegation: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  voterSnapshotBalance: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasVoted: boolean;
        support: boolean;
        tokenWeight: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_TOKEN_TO_VOTE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "amendments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, boolean, string] & {
        proposalId: bigint;
        title: string;
        description: string;
        proposedBy: string;
        timestamp: bigint;
        approved: boolean;
        status: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "approveAmendment"
  ): TypedContractMethod<[_amendmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveExecution"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assignRole"
  ): TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _duration: BigNumberish,
      _category: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delegateVote"
  ): TypedContractMethod<[_delegate: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "delegators"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "executeProposal"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executionApprovals"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAmendment"
  ): TypedContractMethod<
    [_amendmentId: BigNumberish],
    [ProposalVoting.AmendmentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDelegate"
  ): TypedContractMethod<[_voter: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEffectiveVotingPower"
  ): TypedContractMethod<[_voter: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMultiSigDetails"
  ): TypedContractMethod<
    [],
    [[string[], bigint] & { approvers: string[]; required: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_proposalId: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        string,
        boolean,
        string,
        bigint
      ] & {
        title: string;
        description: string;
        yesVotes: bigint;
        noVotes: bigint;
        deadline: bigint;
        status: string;
        creator: string;
        isVotingOpen: boolean;
        category: string;
        approvalsGiven: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalAmendments"
  ): TypedContractMethod<[_proposalId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposalSnapshotBlock"
  ): TypedContractMethod<[_proposalId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposals"
  ): TypedContractMethod<
    [],
    [
      [
        string[],
        string[],
        bigint[],
        bigint[],
        bigint[],
        string[],
        string[],
        string[]
      ] & {
        titles: string[];
        descriptions: string[];
        yesVotes: bigint[];
        noVotes: bigint[];
        deadlines: bigint[];
        statuses: string[];
        creators: string[];
        categories: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposalsByCategory"
  ): TypedContractMethod<[_category: string], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getProposalsByStatus"
  ): TypedContractMethod<[_status: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUserRole"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasVoted: boolean;
        support: boolean;
        tokenWeight: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterSnapshotBalance"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVoterStats"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [
      [boolean, bigint, bigint] & {
        participated: boolean;
        tokenUsed: bigint;
        votingPower: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "governanceToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [_user: AddressLike, _role: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _voter: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "multiSigApprovers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalAmendments"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        string,
        bigint,
        boolean,
        bigint
      ] & {
        title: string;
        description: string;
        yesVotes: bigint;
        noVotes: bigint;
        deadline: bigint;
        status: bigint;
        creator: string;
        category: string;
        snapshotBlock: bigint;
        readyForExecution: boolean;
        amendmentCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalsByCategory"
  ): TypedContractMethod<[arg0: string, arg1: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeAmendment"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _title: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rejectAmendment"
  ): TypedContractMethod<[_amendmentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestExecution"
  ): TypedContractMethod<[_proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requiredApprovals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revokeDelegation"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userRoles"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteDelegation"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "voterSnapshotBalance"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [boolean, boolean, bigint] & {
        hasVoted: boolean;
        support: boolean;
        tokenWeight: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "AmendmentApproved"
  ): TypedContractEvent<
    AmendmentApprovedEvent.InputTuple,
    AmendmentApprovedEvent.OutputTuple,
    AmendmentApprovedEvent.OutputObject
  >;
  getEvent(
    key: "AmendmentProposed"
  ): TypedContractEvent<
    AmendmentProposedEvent.InputTuple,
    AmendmentProposedEvent.OutputTuple,
    AmendmentProposedEvent.OutputObject
  >;
  getEvent(
    key: "AmendmentRejected"
  ): TypedContractEvent<
    AmendmentRejectedEvent.InputTuple,
    AmendmentRejectedEvent.OutputTuple,
    AmendmentRejectedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionApproved"
  ): TypedContractEvent<
    ExecutionApprovedEvent.InputTuple,
    ExecutionApprovedEvent.OutputTuple,
    ExecutionApprovedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutionRequested"
  ): TypedContractEvent<
    ExecutionRequestedEvent.InputTuple,
    ExecutionRequestedEvent.OutputTuple,
    ExecutionRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MultiSigSetup"
  ): TypedContractEvent<
    MultiSigSetupEvent.InputTuple,
    MultiSigSetupEvent.OutputTuple,
    MultiSigSetupEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalRejected"
  ): TypedContractEvent<
    ProposalRejectedEvent.InputTuple,
    ProposalRejectedEvent.OutputTuple,
    ProposalRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAssigned"
  ): TypedContractEvent<
    RoleAssignedEvent.InputTuple,
    RoleAssignedEvent.OutputTuple,
    RoleAssignedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCasted"
  ): TypedContractEvent<
    VoteCastedEvent.InputTuple,
    VoteCastedEvent.OutputTuple,
    VoteCastedEvent.OutputObject
  >;
  getEvent(
    key: "VoteDelegated"
  ): TypedContractEvent<
    VoteDelegatedEvent.InputTuple,
    VoteDelegatedEvent.OutputTuple,
    VoteDelegatedEvent.OutputObject
  >;
  getEvent(
    key: "VoteDelegationRevoked"
  ): TypedContractEvent<
    VoteDelegationRevokedEvent.InputTuple,
    VoteDelegationRevokedEvent.OutputTuple,
    VoteDelegationRevokedEvent.OutputObject
  >;

  filters: {
    "AmendmentApproved(uint256,uint256)": TypedContractEvent<
      AmendmentApprovedEvent.InputTuple,
      AmendmentApprovedEvent.OutputTuple,
      AmendmentApprovedEvent.OutputObject
    >;
    AmendmentApproved: TypedContractEvent<
      AmendmentApprovedEvent.InputTuple,
      AmendmentApprovedEvent.OutputTuple,
      AmendmentApprovedEvent.OutputObject
    >;

    "AmendmentProposed(uint256,uint256,address)": TypedContractEvent<
      AmendmentProposedEvent.InputTuple,
      AmendmentProposedEvent.OutputTuple,
      AmendmentProposedEvent.OutputObject
    >;
    AmendmentProposed: TypedContractEvent<
      AmendmentProposedEvent.InputTuple,
      AmendmentProposedEvent.OutputTuple,
      AmendmentProposedEvent.OutputObject
    >;

    "AmendmentRejected(uint256,uint256)": TypedContractEvent<
      AmendmentRejectedEvent.InputTuple,
      AmendmentRejectedEvent.OutputTuple,
      AmendmentRejectedEvent.OutputObject
    >;
    AmendmentRejected: TypedContractEvent<
      AmendmentRejectedEvent.InputTuple,
      AmendmentRejectedEvent.OutputTuple,
      AmendmentRejectedEvent.OutputObject
    >;

    "ExecutionApproved(uint256,address)": TypedContractEvent<
      ExecutionApprovedEvent.InputTuple,
      ExecutionApprovedEvent.OutputTuple,
      ExecutionApprovedEvent.OutputObject
    >;
    ExecutionApproved: TypedContractEvent<
      ExecutionApprovedEvent.InputTuple,
      ExecutionApprovedEvent.OutputTuple,
      ExecutionApprovedEvent.OutputObject
    >;

    "ExecutionRequested(uint256)": TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;
    ExecutionRequested: TypedContractEvent<
      ExecutionRequestedEvent.InputTuple,
      ExecutionRequestedEvent.OutputTuple,
      ExecutionRequestedEvent.OutputObject
    >;

    "MultiSigSetup(address[],uint8)": TypedContractEvent<
      MultiSigSetupEvent.InputTuple,
      MultiSigSetupEvent.OutputTuple,
      MultiSigSetupEvent.OutputObject
    >;
    MultiSigSetup: TypedContractEvent<
      MultiSigSetupEvent.InputTuple,
      MultiSigSetupEvent.OutputTuple,
      MultiSigSetupEvent.OutputObject
    >;

    "ProposalCreated(uint256,string,address,uint64,string)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint256)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "ProposalRejected(uint256)": TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;
    ProposalRejected: TypedContractEvent<
      ProposalRejectedEvent.InputTuple,
      ProposalRejectedEvent.OutputTuple,
      ProposalRejectedEvent.OutputObject
    >;

    "RoleAssigned(address,uint8)": TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;
    RoleAssigned: TypedContractEvent<
      RoleAssignedEvent.InputTuple,
      RoleAssignedEvent.OutputTuple,
      RoleAssignedEvent.OutputObject
    >;

    "RoleRevoked(address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "VoteCasted(uint256,address,bool,uint64)": TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;
    VoteCasted: TypedContractEvent<
      VoteCastedEvent.InputTuple,
      VoteCastedEvent.OutputTuple,
      VoteCastedEvent.OutputObject
    >;

    "VoteDelegated(address,address)": TypedContractEvent<
      VoteDelegatedEvent.InputTuple,
      VoteDelegatedEvent.OutputTuple,
      VoteDelegatedEvent.OutputObject
    >;
    VoteDelegated: TypedContractEvent<
      VoteDelegatedEvent.InputTuple,
      VoteDelegatedEvent.OutputTuple,
      VoteDelegatedEvent.OutputObject
    >;

    "VoteDelegationRevoked(address)": TypedContractEvent<
      VoteDelegationRevokedEvent.InputTuple,
      VoteDelegationRevokedEvent.OutputTuple,
      VoteDelegationRevokedEvent.OutputObject
    >;
    VoteDelegationRevoked: TypedContractEvent<
      VoteDelegationRevokedEvent.InputTuple,
      VoteDelegationRevokedEvent.OutputTuple,
      VoteDelegationRevokedEvent.OutputObject
    >;
  };
}
