/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as counterSol from "./Counter.sol";
export { GovernanceToken__factory } from "./GovernanceToken__factory";
